### ISSUE TITLE
Size of mpk

### ISSUE THREAD

**Issue by RoelandSalij** [WebFlight/DeepObjectAssert#1]
This looks like a great contribution to the App Store! Thank you for that.

One question: 
Not all the jars currently in the userlib folder seem to be necessary.
There are for example jars which are included in community commons already, so you won't need to include those in your mpk too. I'm also not sure if the bytebuddy jars, which are included currently, are required.

As a result the mpk is over 37 MB. Is that something that can be reduced by removing the unused jars from the package?

**Comment by mennodehaas** [comment]
@RoelandSalij Thanks for your feedback. Bytebuddy and Mockito are used for JUnit testing. We now excluded all testing code from the MPK. The filesize is now just over 5MB.
